import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";
import { Outfit } from "next/font/google";
import "./globals.css";
import Provider from "./provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          {/* SignedOut durumunda kullanıcıya giriş yapma butonu */}
          <SignedOut>
            <div className="flex justify-center items-center h-screen">
              <SignInButton />
            </div>
          </SignedOut>
          {/* SignedIn durumunda kullanıcı butonu */}
          <SignedIn
            appearance={{
              elements: {
                button: "w-full flex flex-col gap-2", // Tailwind sınıfları ekle
              },
            }}
          >
            <header className="flex justify-between items-center p-4">
              <h1 className="text-xl font-bold">Welcome to the App</h1>
              <UserButton />
            </header>
            <Provider>{children}</Provider>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
